# Generated by Django 5.2.1 on 2025-05-18 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('churn_probability', models.FloatField()),
                ('predicted_churn', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to='data_processor.customer')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
