# Generated by Django 5.2.1 on 2025-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('creditscore', models.IntegerField()),
                ('geography', models.CharField(choices=[('France', 'France'), ('Spain', 'Spain'), ('Germany', 'Germany')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('balance', models.FloatField()),
                ('numofproducts', models.IntegerField()),
                ('hascrcard', models.BooleanField()),
                ('isactivemember', models.BooleanField()),
                ('estimatedsalary', models.FloatField()),
                ('exited', models.BooleanField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
